---
title: "Reliability of Infant Research"
output: html_notebook
---



```{r}

library(tidyverse)
library(pwr)

```

## Figure 1 - simulation of hypothetical datasets

# Simulate samples of infants
```{r simulate}

set.seed(100)
size = 50

my_mean <- 1 # Mean of all simulated datasets
sd_true_small <- .5
sd_true_large <- 1
sd_error_small <- .5
sd_error_large <- 1


# Use distribution_normal to get a distribution that is as close as possible to canonical normal distribution
#scores_true_stable <- rep(1, size) # sd = 0; variance = 0
scores_true_stable <- distribution_normal(size, mean = my_mean, sd = sd_true_small) 
scores_true_variable <- distribution_normal(size, mean = my_mean, sd = sd_true_large) # sd = 1, variance = 1
#true_variability_low <- rep("low", size)
#true_variability_high <- rep("high", size)

# sample creates a random permutation to scramble the errors

meas_err_small <- sample(distribution_normal(size, mean = 0, sd = sd_error_small)) # sd = .5 variance = .25)
meas_err_large <- sample(distribution_normal(size, mean = 0, sd = sd_error_large)) # sd = 1, variance = 1)
err_large <- rep("large", size)
err_small <- rep("small", size)

# Calculate observed scores

obs_scores_stable_small <- scores_true_stable + meas_err_small
obs_scores_stable_large <- scores_true_stable + meas_err_large

obs_scores_variable_small <- scores_true_variable + meas_err_small
obs_scores_variable_large <- scores_true_variable + meas_err_large

# Create dataframes for

sim_data_stable <- as.data.frame(cbind(scores_true_stable, meas_err_small, meas_err_large)) %>%
  mutate(true_variability = "low") %>%
  rename(scores_true = scores_true_stable) %>%
  mutate(scores_err_large = scores_true + meas_err_large) %>%
  mutate(scores_err_small = scores_true + meas_err_small) %>%
  pivot_longer(names_to = "error", values_to = "scores_observed", cols = c(scores_err_small, scores_err_large), names_prefix = "scores_err_") 

sim_data_variable <- as.data.frame(cbind(scores_true_variable, meas_err_small, meas_err_large)) %>%
  mutate(true_variability = "high") %>%
  rename(scores_true = scores_true_variable) %>%
  mutate(scores_err_large = scores_true + meas_err_large) %>%
  mutate(scores_err_small = scores_true + meas_err_small) %>%
  pivot_longer(names_to = "error", values_to = "scores_observed", cols = c(scores_err_small, scores_err_large), names_prefix = "scores_err_") 


sim_data <- rbind(sim_data_stable, sim_data_variable) %>%
  mutate(error = as.factor(error), true_variability = as.factor(true_variability)) %>%
  group_by(error, true_variability) %>%
  arrange(true_variability, error, scores_true, scores_observed) %>%
  mutate(id = row_number()) %>%
  pivot_longer(names_to = "scores_type", values_to = "score", cols = c("scores_true", "scores_observed"), names_prefix = "scores_")




```

# Reshape data for plotting
```{r reshape}

# Observed Cohen's d

sim_data_summary <- sim_data %>%
  group_by(scores_type, true_variability, error) %>%
  summarize(mean = mean(score), sd = sd(score), d = mean/sd)


d_stable_small <- mean(obs_scores_stable_small)/sd(obs_scores_stable_small)
d_stable_large <- mean(obs_scores_stable_large)/sd(obs_scores_stable_large)

d_variable_small <- mean(obs_scores_variable_small)/sd(obs_scores_variable_small)
d_variable_large <- mean(obs_scores_variable_large)/sd(obs_scores_variable_large)

# Observed reliabilities

rel_stable_small <- var(scores_true_stable)/(var(scores_true_stable) + var(meas_err_small))
rel_stable_large <- var(scores_true_stable)/(var(scores_true_stable) + var(meas_err_large))

rel_variable_small <- var(scores_true_variable)/(var(scores_true_variable) + var(meas_err_small))
rel_variable_large <- var(scores_true_variable)/(var(scores_true_variable) + var(meas_err_large))

# Theoretical

true_data_summary <- sim_data %>%
  distinct(true_variability, error) %>%
  mutate(mean = my_mean) %>%
  mutate(scores_type = "true") %>%
  mutate(sd_true = case_when(
         true_variability == "low" ~ sd_true_small,
         true_variability == "high" ~ sd_true_large)) %>%
  mutate(sd_err = case_when(
    error == "small" ~ sd_true_small,    
    error == "large" ~ sd_true_large)) %>%
  mutate(var = sd_err^2 + sd_true^2) %>%
  mutate(sd = sqrt(var)) %>%
  mutate(d = mean/sd) %>%
  mutate(r = sd_true^2/var)


```





# Plot data
```{r plot}



true_variability_labs <- c("high true variability (sd = 1)", "low true variability (sd = .5)")
names(true_variability_labs) <- c("high", "low")


error_labs <- c("large measurement error (sd = 1)", "small measurement error (sd = .5)")
names(error_labs) <- c("large", "small")

expr <- as.character(expression('r'[xx]))

sim_plot <- sim_data %>%
  ggplot(aes(x = fct_rev(scores_type), y = score)) +
  geom_hline(yintercept = 0, lty = "dashed") +
  geom_line(aes(group = id), color = "grey") +
  geom_point(aes(color = scores_type)) +
  facet_grid(true_variability ~ error, labeller=labeller(true_variability = true_variability_labs, error = error_labs)) +
    theme_few() +
  scale_x_discrete("Score type") +
  ylim(-3, 4) +
  theme(legend.position = "none", text = element_text(size=12)) +
  geom_label(data = true_data_summary, 
             y = -3, 
             label.size = NA, 
             label.padding = unit(.1, "lines"), 
             alpha = 0, 
             vjust = "bottom", 
             nudge_x = .5, 
             size = 3, 
             aes(label = (paste("Mean = ", mean, ", sd = ", round(sd, 2), ", d = ", round(d, 2), ", r\u2093\u2093  = ", round(r, 2))))) # To get subscripts, use unicode
             

ggsave("reliability_plot.png", width = 8.5, height = 5, units = "in", dpi = 300)
```
## Table 1 - Sample size and power

```{r}

# Compute necessary sample sizes at different levels of Cohen's d


# d = .2

pwr.t.test(d = .2, power = .8)

# d = .4

pwr.t.test(d = .4, power = .8)

# d = .6

pwr.t.test(d = .6, power = .8)

# d = .8

pwr.t.test(d = .8, power = .8)

#d = 1

pwr.t.test(d = 1, power = .8)


```

